spring:
  application:
    name: rag-pgvector-example

  datasource:
    url: jdbc:postgresql://59.110.45.189:5432/postgres
    username: postgres
    password: mysecretpassword

  ai:
    dashscope:
      api-key: sk-c12921649fe24d8587df7088626b34ff
    vectorstore:
      pgvector:
        dimensions: 1536
        index-type: hnsw
        distance-type: cosine_distance
